# Tensor Basics

<p> In this notebook we are going to learn all about tensors. We will see how to create tensors, how to use them, and how to manipulate them. It is a very important building block for working with pytorch and making our own artifical neural networks </p>

### Importing pytorch


In [2]:
# Importing pytorch
import torch

### Uninitializing tensors

In [3]:
x = torch.empty(1) # Uninitialized tensor with one empty value
print(x)

x = torch.empty(3) # We can change the size to our own needs
print(x)

tensor([0.])
tensor([0., 0., 0.])


### Increasing the dimension of a tensor

In [4]:
# We can increase the dimensions of the tensor as well

x = torch.empty(2, 2) # 2D tensor
y = torch.empty(2,3,2) # 3D tensor

print(x)
print(y)

tensor([[0., 0.],
        [0., 0.]])
tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])


### Random Values, Zeros, Ones

In [5]:
# We can initialize the tensor with random values

x = torch.rand(2,2)
print(x)

tensor([[0.0523, 0.7831],
        [0.1880, 0.2493]])


In [6]:
# We can initialize the tensor with zeros
x = torch.zeros(2,2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [11]:
# We can initialize tensor with ones
x = torch.ones(2,2)
print(x)
print(x.dtype)

tensor([[1., 1.],
        [1., 1.]])
torch.float32


### Changing the datatype of a tensor

In [10]:
# We can change the data type of the tensor
x = torch.ones(2,2, dtype=torch.int) # We can change the data type to int, float, double, etc
print(x.dtype)

torch.int32


### Finding size() of the tensor

In [12]:
x = torch.ones(2,2, dtype=torch.double)
print(x.size())

torch.Size([2, 2])


### Directly creating a tensor

In [15]:
x = torch.Tensor([2.5, 3., 4.]) # We can initialize the tensor with a list of values
print(x)

tensor([2.5000, 3.0000, 4.0000])


### Adding tensors

In [19]:
x = torch.Tensor([[1., 0.5], [.6, 2.]])
y = torch.rand(2,2)
print(x)
print(y)
z = x + y
print(z)

# We can also add one tensor to another without storing it in a new variable
x.add_(y)
print(x)

# We can also use the torch.add() function to add two tensors
z = torch.add(x, y)
print(z)


tensor([[1.0000, 0.5000],
        [0.6000, 2.0000]])
tensor([[0.7971, 0.0943],
        [0.1717, 0.4345]])
tensor([[1.7971, 0.5943],
        [0.7717, 2.4345]])
tensor([[1.7971, 0.5943],
        [0.7717, 2.4345]])
tensor([[2.5943, 0.6887],
        [0.9434, 2.8690]])
